#!/usr/bin/env bash

declare test_directory bats_executable

test_directory="$(cd "$(dirname "$0")" && pwd)"
bats_executable="${test_directory}/../bin/bats-core/bin/bats"

git submodule init && git submodule update

if [[ -z "${GAUDI_BASH}" ]]; then
  declare GAUDI_BASH
  GAUDI_BASH=$(cd "${test_directory}" && dirname "$(pwd)")
  export GAUDI_BASH
fi

# Capture all the test files by searching the lib folder for .bats files
if [[ -z "$1" ]]; then
  shopt -s globstar
  for lib in "${test_directory}"/**/*.bats; do
    test_dirs+=("$lib")
  done
else
  test_dirs=( "$1" )
fi

exec "$bats_executable" ${CI:+--tap} "${test_dirs[@]}"
