name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, macos-14, macos-15]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies (macOS)
      if: startsWith(runner.os, 'macOS')
      run: |
        brew install coreutils parallel

    - name: Install dependencies (Linux)
      if: startsWith(runner.os, 'Linux')
      run: |
        sudo apt-get update
        sudo apt-get install -y parallel

    - name: Run tests (Linux)
      if: startsWith(runner.os, 'Linux')
      shell: 'script -q -e -c "bash {0}"'
      run: test/run

    - name: Run tests (macOS)
      if: startsWith(runner.os, 'macOS')
      run: script -q /dev/null bash -c 'test/run'

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: Install shfmt
      run: |
        curl -sS https://webi.sh/shfmt | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install pre-commit
      run: python3 -m pip install pre-commit

    - name: Run lint
      run: pre-commit run --all-files
